package io.quarkus.ts.opentelemetry;

import static io.restassured.RestAssured.given;
import static org.awaitility.Awaitility.await;
import static org.hamcrest.Matchers.equalTo;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.apache.http.HttpStatus;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import io.quarkus.test.bootstrap.RestService;
import io.quarkus.test.scenarios.QuarkusScenario;
import io.quarkus.test.services.QuarkusApplication;

@Tag("QUARKUS-5623")
@QuarkusScenario
public class OpenTelemetryLoggingIT {
    private static final String SERVICE_NAME = "logging-app";

    private static final String CUSTOM_ATTRIBUTE_VALUE = "Lorem-ipsum";
    private static final Integer BULK_SIZE = 10;

    //    @GrafanaContainer()
    //    static final GrafanaService grafana = new GrafanaService();
    static final OpenTelemetryCollector collector = new OpenTelemetryCollector();

    @QuarkusApplication
    static final RestService app = new RestService()
            .withProperty("quarkus.otel.logs.enabled", "true")
            .withProperty("quarkus.log.level", "DEBUG")
            .withProperty("quarkus.application.name", SERVICE_NAME)
            .withProperty("quarkus.otel.resource.attributes", "custom_attribute=" + CUSTOM_ATTRIBUTE_VALUE)
            .withProperty("quarkus.otel.blrp.schedule.delay", "PT5S")
            .withProperty("quarkus.otel.blrp.max.export.batch.size", BULK_SIZE.toString())
            .withProperty("quarkus.otel.exporter.otlp.logs.endpoint", collector::url);

    @Test
    public void shouldSendReportInBulks() throws InterruptedException {
        try (collector) {
            // this test uses only warning level messages, to filter debug messages, generated by the framework, which may skew asserts
            // period how often so send log lines is configured by "quarkus.otel.blrp.schedule.delay" property

            // count log lines reported before test starts
            int initLogLines = getWarningLogCount(0);

            // generate just a few lines, less that size of bulk
            app.given().get("/logging/generate/two")
                    .then()
                    .statusCode(HttpStatus.SC_OK)
                    .body(equalTo("Lines generated"));

            await().atMost(7, TimeUnit.SECONDS).untilAsserted(() -> {
                assertEquals(initLogLines + 2, getWarningLogCount(initLogLines + 2),
                        "Lines should arrive within sending interval");
            });

            // generate more lines that fit more than one bulk
            app.given().get("/logging/generate/twenty")
                    .then()
                    .statusCode(HttpStatus.SC_OK)
                    .body(equalTo("Lines generated"));

            // messages are more than one bulk, so at least one bulk should be sent soon
            await().atMost(2, TimeUnit.SECONDS).untilAsserted(() -> {
                assertTrue(getWarningLogCount(initLogLines + 2 + BULK_SIZE) >= initLogLines + 2 + BULK_SIZE,
                        "Bulk of log lines should arrive soon");
            });

            // all messages should arrive in at most one sending period
            await().atMost(7, TimeUnit.SECONDS).untilAsserted(() -> {
                assertEquals(initLogLines + 22, getWarningLogCount(initLogLines + 22),
                        "All logged lines should arrive withing sending interval");
            });

            Thread.sleep(5000);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    protected void validateHostname(LogEntry logEntry) throws UnknownHostException {
        String hostname = InetAddress.getLocalHost().getHostName();
        assertEquals(hostname, logEntry.hostname, "Hostname in the logs should be local machine hostname");
    }

    private int getWarningLogCount(int expected) {
        return expected;
    }
    //
    //    private Response retrieveAllLogs(String serviceName) {
    //        return given().when()
    //                .queryParam("query", "{service_name=\"" + serviceName + "\"}")
    //                .queryParam("limit", 500)
    //                .get(grafana.getRestUrl() + "/loki/api/v1/query_range");
    //    }
    //
    //    private Response retrieveWarnings(String serviceName) {
    //        return given().when()
    //                .queryParam("query", "{service_name=\"" + serviceName + "\"} |= \"warning\"")
    //                .queryParam("limit", 500)
    //                .get(grafana.getRestUrl() + "/loki/api/v1/query_range");
    //    }

    private List<LogEntry> parseJsonLogs(List<Map> restAssuredResult) {
        List<LogEntry> result = new ArrayList<>();

        for (Map map : restAssuredResult) {
            result.add(new LogEntry(
                    ((Map) map.get("stream")).get("severity_text").toString(),
                    // element number 0 is timestamp, to get text we get element number 1 from values
                    ((List<List<String>>) map.get("values")).get(0).get(1),
                    ((Map<?, ?>) map.get("stream")).get("host_name").toString(),
                    ((Map<?, String>) map.get("stream")).getOrDefault("custom_attribute", "").toString()));
        }

        return result;
    }

    private record ExpectedEntry(String severity, String text) {

    }

    protected record LogEntry(String severity, String text, String hostname, String customAttribute) {
        @Override
        public String hostname() {
            return hostname;
        }
    }
}
