quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=QuArKuS_tEsT
quarkus.flyway.schemas=msdb
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=msdb
quarkus.flyway.locations=db/migration/mssql,db/migration/common
quarkus.datasource.jdbc.additional-jdbc-properties.trustServerCertificate=true
quarkus.flyway.migrate-at-start=true
