quarkus.datasource.mssql.db-kind=mssql
quarkus.datasource.mssql.username=sa
quarkus.datasource.mssql.password=QuArKuS_tEsT
quarkus.flyway.mssql.schemas=msdb
quarkus.datasource.mssql.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=msdb
quarkus.flyway.mssql.locations=db/migration/mssql,db/migration/common
