quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.additional-jdbc-properties.trustServerCertificate=true
quarkus.datasource.username=sa
quarkus.datasource.password=My1337p@ssworD
quarkus.flyway.schemas=msdb
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration/shared
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433
