GRANT SELECT ON V$XATRANS$ TO myuser;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO myuser;
GRANT FORCE ANY TRANSACTION TO myuser;
GRANT FORCE TRANSACTION TO myuser;

CREATE OR REPLACE DIRECTORY XA_TRACE_DIR AS '/tmp/xa';
GRANT READ, WRITE ON DIRECTORY XA_TRACE_DIR TO myuser;
