name: "PR"
on:
  - pull_request
jobs:
  linux-build-jvm-latest:
    name: Linux JVM
    runs-on: ubuntu-latest
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        java: [ 17 ]
        module-mvn-args: ${{ fromJSON(needs.prepare-jvm-native-latest-modules-mvn-param.outputs.JVM_MODULES_MAVEN_PARAM) }}
    outputs:
      has-flaky-tests: ${{steps.flaky-test-detector.outputs.has-flaky-tests}}
    steps:
      - uses: actions/checkout@v5
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Install JDK {{ matrix.java }}
        # Uses sha for added security since tags can be updated
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'maven'
      - uses: ./.github/actions/prepare-quarkus-cli
      - uses: ./.github/actions/use-docker-mirror
      - name: Build with Maven
        run: |
          mvn -fae -V -B --no-transfer-progress clean verify -Dinclude.quarkus-cli-tests -Dts.quarkus.cli.cmd="${PWD}/quarkus-dev-cli" -pl http/management -am
      - name: Detect flaky tests
        id: flaky-test-detector
        if: ${{ hashFiles('**/flaky-run-report.json') != '' }}
        run: echo "has-flaky-tests=true" >> "$GITHUB_OUTPUT"
      - name: Rename flaky test run report to avoid file name conflicts
        id: rename-flaky-test-run-report
        if: ${{ hashFiles('**/flaky-run-report.json') != '' }}
        shell: bash
        run: mv target/flaky-run-report.json target/flaky-run-report-linux-jvm-latest.json
      - name: Archive flaky run report
        id: archive-flaky-run-report
        if: ${{ hashFiles('**/flaky-run-report-linux-jvm-latest.json') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: flaky-run-report-linux-jvm-latest
          path: target/flaky-run-report-linux-jvm-latest.json
      - name: Zip Artifacts
        if: failure()
        run: |
          zip -R artifacts-latest-linux-jvm${{ matrix.java }}.zip '*-reports/*'
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: artifacts-latest-linux-jvm${{ matrix.java }}
          path: artifacts-latest-linux-jvm${{ matrix.java }}.zip
