name: "Daily Build"
on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'
jobs:
  aarch64-linux-build-jvm-latest:
    name: Linux AArch64 JVM
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 21 ]
        profiles: [ "root-modules", "http-modules,security-modules,spring-modules", "hibernate-modules",
                    "sql-db-modules", "root-modules -pl build/podman/,build/docker -Dtest-ubi8-compatibility",
                    "messaging-modules,websockets-modules,monitoring-modules,cache-modules,test-tooling-modules,nosql-db-modules"]
    steps:
      - uses: actions/checkout@v5
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
          cache: 'maven'
      - uses: ./.github/actions/prepare-quarkus-cli
      - uses: ./.github/actions/use-docker-mirror
      - name: Login to Red Hat registry
        uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RED_HAT_REGISTRY_USERNAME }}
          password: ${{ secrets.RED_HAT_REGISTRY_PASSWORD }}
      - name: Test in JVM mode
        run: |
          mvn -fae -V -B --no-transfer-progress -fae clean verify -Daarch64 -pl http/http-advanced -Dit.test=DevModeWorkspaceIT -P ${{ matrix.profiles }} -Dinclude.quarkus-cli-tests -Dts.quarkus.cli.cmd="${PWD}/quarkus-dev-cli"
      - name: Zip Artifacts
        if: failure()
        run: |
          zip -R artifacts-linux-aarch64-jvm${{ matrix.java }}.zip '*-reports/*'
      - name: Archive artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-linux-aarch64-jvm${{ matrix.java }}
          path: artifacts-linux-aarch64-jvm${{ matrix.java }}.zip
